language: node_js
node_js:
  - '13'
  - '12'
install:
  - yarn install --frozen-lockfile
script:
  - yarn run test
deploy:
  provider: npm
  email: info@pascal-iske.de
  api_key:
    secure: XBF7DkkhdvXRLo/pqDrteZGqnPqABctrbN3/AqNXkLxB0bhLAJWr6UQXBoOm1cVNGC5h6E48+UVxYAj/3Vz/giS7pB0LQTOkgzhL5o6Ione29a85ErjQ4/l5hRWwsnuikYS/S61divGpeKuvyBmexcYc8RnlZmBhistGrLE+QWYpvzhgCTR3yniBHvl8sDr/icWdI2D4tt7MmZo3rpaRse6OXeiblUF99xoquM64tZSe/lWac5mlvRj1MZaEMtKhhJIqU414JNmY3hPJ7UWBuMnMVO953heV7yKzbR27KZnWZVSEZwtDJ1S+R7IrR2kW26MPX7qrYssIwjeUVPxKtuuSAfB9mg07pJZMgELacZEMBpeWNmhsq/vJmYEaS1K1rnrgNQ2bVoa/Z8gIe8vMFH5zc719m/md2DfqVax7f4/CggAg401sVIojJlorancx2PHt7SPIoZ0mS+Yd+kM616ifRTa5gtR2y4sPcxrrAMc24hKm4/KfUM7+WsHklWrrDVSCaQpu+41GPbs4dPVAihByqJ24iM8VZZ2rCDFX6UQ7ymwqhFB++tEY5buI1C31kdI9NwXrv5Tiw+CHQqD4/hHyRADEq1ecomtiK2nXiBgAuurydM4ugfPdOdEoMhLFMbx5amBmbKblAYrHvMzucXfAZf4RGyuHxUYc4qYYA64=
  on:
    tags: true
    branch: master
    node: 13
env:
  global:
    - secure: Ugcvy60xS+L/aan1zFoJDrgpsYEQcc+1hZce8nXon19FrbKymooXVlvrkAy0sRxrcsNBUpTG6jIKikAxsHAAsM/kP5J8WKV5Duu70RnAP+uMoJcgNnzJtu5qEAobxZ3VRCWfB4G+lDYkOxKqcob7wrkeGrEqrbC344BY0BrXHWcGk+gY/EiuWMDruDFZFPuksD7FV4y1h+qcCx5Yto1NhHJ3vZXIYpy2Kqrnkr/OKHg53N8S9R45eLzNFNse/h5ja2GzVrwVkBNNX2XnYXl/F61dnQ+v7UzInMJcBgifHleY7Ps3wKsc+gLEYJydhCZD/YAHdizdZFIxYjytFscHKrMMozbkCdOVzsBfN0i0LzOrVDhrX1lpfJ0Yh/Ly0oI7AZg+C87IMWNeg/vTsqhUIcIi61TWoAIx8J+RW7DrMSEs5rrTDipHwRez1zrG6hJBj8WSSYa+mC2rk2HcPa1Jv+jod+/uk3/F2Bdck1vaiW2gIluSAlWwMJq6cOMlJJwlhQArZMYg4hgYUpJ5x1oYMOIX+pNukCDufRkepDo5ASfx5rIyWEi4cgVnjmXGZlyRi1+Mus2YqB7GQ4air2nj0CUuDg5CTcZ4KYHpDBARDxKnZMTqCm9n4WN2w59eniHJIUTyD8F0jue9V76foI3z0KUg+hWOgyIlCejN8lYUGUQ=
